INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Комаров Арсений', 'Азбука спорта', '2012-2013', 3, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Родько Даниил', 'Гермес', '2012-2013', 2, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Батуев Дмитрий', 'Гермес', '2012-2013', 1, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Меркулов Михаил', 'Взлет', '2012-2013', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Сенаторов Артем', 'Азбука спорта', '2012-2013', 1, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Шеин Артем', 'Азбука спорта', '2012-2013', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Сергиенко Александр', 'Взлет', '2011-2012', 3, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Давыдов Станислав', 'Сокол-Сервантинос', '2011-2012', 2, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Меркулов Михаил', 'Взлет', '2011-2012', 2, 2, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Горбунов Матвей', 'Взлет', '2011-2012', 1, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Припоров Платон', 'Время первых', '2011-2012', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Савинов Евгений', 'Пилот', '2011-2012', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Садулаев Дени', 'Пилот', '2011-2012', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Лосев Максим', 'Пантеры', '2011-2012', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Наумов Артем', 'Сокол-Сервантинос', '2011-2012', 1, 2, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Антонюк Антон', 'Сокол-Сервантинос', '2011-2012', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Дробков Николай', 'Сокол-Сервантинос', '2011-2012', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Коннов Платон', 'Сокол-Сервантинос', '2011-2012', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Перфильев Даниил', 'Сокол-Сервантинос', '2011-2012', 1, 0, 1, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Павлов Тимофей', 'Пантеры', '2011-2012', 1, 0, 1, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Мячин Александр', 'Олимп', '2013-2014', 3, 2, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Муферт Александр', 'Взлет', '2013-2014', 2, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Рябов Юрий', 'Пилот', '2013-2014', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Ушаков Иван', 'Пилот', '2013-2014', 1, 0, 0, 0);