INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Чичилеишвили Николай', 'Буря', '2013-2014', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Пехтерев Николай', 'Буря', '2013-2014', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Сапрыкин Алексей', 'Взлет', '2013-2014', 1, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Магдалина Вадим', 'Взлет', '2013-2014', 1, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Нартикоев Роберт', 'Взлет', '2013-2014', 1, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Черендин Никита', 'Взлет', '2013-2014', 1, 2, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Барченков Никита', 'Сокол-Сервантинос', '2013-2014', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Кулаков Владимир', 'Олимп', '2013-2014', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Липунов Иван', 'Олимп', '2013-2014', 1, 1, 1, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Нестеренко Семен', 'Олимп', '2013-2014', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Романов Кирилл', 'Олимп', '2013-2014', 1, 0, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Гольцов Кирилл', 'Азбука спорта', '2012-2013', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Евтропов Егор', 'Гермес', '2012-2013', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Житинский Артем', 'Азбука спорта', '2012-2013', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Мамедов Максим', 'Азбука спорта', '2012-2013', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Сергиенко Александр', 'Взлет', '2012-2013', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Цыбренко Николай', 'Взлет', '2011-2012', 0, 3, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Орлов Василий', 'Сокол-Сервантинос', '2011-2012', 0, 3, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Ли Адриан', 'Пилот', '2011-2012', 0, 2, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Авакимьянц Добрыня', 'Буря', '2013-2014', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Монахов Кирилл', 'Буря', '2013-2014', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Яковлев Федор', 'Сокол-Сервантинос', '2013-2014', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Чебанян Кирилл', 'Олимп', '2013-2014', 0, 1, 0, 0);
INSERT INTO season_player_stats (name, team, age_group, goals, assists, yellow, red) VALUES ('Закипнев Сергей', 'САО', '2013-2014', 0, 0, 1, 0);