INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (22, 0, 'Горбунов Матвей', 'Меркулов Михаил', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (22, 0, 'Меркулов Михаил', 'Горбунов Матвей', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (22, 0, 'Меркулов Михаил', 'Цыбренко Николай', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (22, 0, 'Сергиенко Александр', 'Меркулов Михаил', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (22, 0, 'Сергиенко Александр', 'Цыбренко Николай', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (22, 0, 'Сергиенко Александр', 'Цыбренко Николай', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (22, 0, 'Припоров Платон', '', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Лосев Максим', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Павлов Тимофей', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (21, 0, 'Савинов Евгений', 'Ли Адриан', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (21, 0, 'Садулаев Дени', 'Ли Адриан', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Антонюк Антон', 'Наумов Артем', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Давыдов Станислав', 'Наумов Артем', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Давыдов Станислав', 'Орлов Василий', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Дробков Николай', 'Орлов Василий', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Коннов Платон', 'Орлов Василий', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Наумов Артем', '', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (25, 0, 'Перфильев Даниил', '', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (23, 0, 'Комаров Арсений', 'Гольцов Кирилл', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (23, 0, 'Комаров Арсений', 'Житинский Артем', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (23, 0, 'Комаров Арсений', 'Мамедов Максим', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (23, 0, 'Сенаторов Артем', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (23, 0, 'Шеин Артем', 'Сенаторов Артем', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (24, 0, 'Меркулов Михаил', 'Сергиенко Александр', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (24, 0, 'Батуев Дмитрий', 'Евтропов Егор', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (24, 0, 'Родько Даниил', 'Батуев Дмитрий', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (24, 0, 'Родько Даниил', '', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (27, 0, 'Пехтерев Николай', 'Авакимьянц Добрыня', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (27, 0, 'Чичилеишвили Николай', 'Монахов Кирилл', 'away', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (28, 0, 'Магдалина Вадим', 'Муферт Александр', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (28, 0, 'Муферт Александр', 'Магдалина Вадим', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (28, 0, 'Муферт Александр', 'Нартикоев Роберт', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (28, 0, 'Нартикоев Роберт', 'Сапрыкин Алексей', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (28, 0, 'Сапрыкин Алексей', 'Черендин Никита', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (28, 0, 'Черендин Никита', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (30, 0, 'Кулаков Владимир', 'Липунов Иван', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (30, 0, 'Липунов Иван', 'Мячин Александр', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (30, 0, 'Мячин Александр', 'Чебанян Кирилл', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (30, 0, 'Мячин Александр', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (30, 0, 'Мячин Александр', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (30, 0, 'Нестеренко Семен', 'Мячин Александр', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (30, 0, 'Романов Кирилл', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (27, 0, 'Рябов Юрий', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (27, 0, 'Ушаков Иван', '', 'home', false);
INSERT INTO match_goals (match_id, minute, player, assist, side, penalty) VALUES (29, 0, 'Барченков Никита', 'Яковлев Федор', 'away', false);
INSERT INTO match_cards (match_id, minute, player, side, color) VALUES (25, 0, 'Павлов Тимофей', 'home', 'yellow');
INSERT INTO match_cards (match_id, minute, player, side, color) VALUES (25, 0, 'Перфильев Даниил', 'away', 'yellow');
INSERT INTO match_cards (match_id, minute, player, side, color) VALUES (30, 0, 'Липунов Иван', 'home', 'yellow');
INSERT INTO match_cards (match_id, minute, player, side, color) VALUES (30, 0, 'Закипнев Сергей', 'away', 'yellow');
UPDATE season_player_stats SET active = false WHERE active = true;